### ISSUE TITLE
Infinite loop when parsing `trait`

### ISSUE THREAD

**Issue by CentaurWarchief** [glayzzle/php-parser#1]
Hey guys, what's up?

I'm struggling with a infinite loop (...and I can't win) when I parse a file that contains `trait`, how can I fix?

Thanks,
Hugs!

:beers:

**Comment by ichiriac** [comment]
Hi Dude,

You can first fork the project, and add a test that shows the bug, lets say you create in `test/parser/trait.parser` file with the following content :

```js
Test the traits parsing
--PASS--
trait ezcReflectionReturnInfo {
    function getReturnType() { /*1*/ }
    function getReturnDescription() { /*2*/ }
}

class ezcReflectionMethod extends ReflectionMethod {
    use ezcReflectionReturnInfo;
    /* ... */
}

class ezcReflectionFunction extends ReflectionFunction {
    use ezcReflectionReturnInfo;
    /* ... */
}
```

And then run test in verbose mode with `node bin/test.js -f test/parser/trait.parser -v`

To find out where traits are implemented search "T_TRAIT" in all code source, you will find out that they are implemented in `src/class/parser.js` ... well, they are not in fact handled.

Fork and try to implement them, I will help you when you will be blocked.

Take a look at the wiki, I will start to explain the parser API

**Comment by CentaurWarchief** [comment]
@ichiriac 

Yes, thanks for the reply and also excuse me for the late answer.
Well, I'll give it a shot later.

**Comment by zxqfox** [comment]
@CentaurWarchief Sorry for pinging, did you tried it?

**Comment by CentaurWarchief** [comment]
@zxqfox 

Hi! I didn't tried, the project that I was needing it was abandoned. Do you need something? I mean, you're intending to try something?

**Comment by zxqfox** [comment]
@CentaurWarchief Yep, trying to parse php expressions and php code to use inside smarty-parser.

That's not about this issue, but in common: 0.0.4 is pretty scary to use. :smirk_cat:

**Comment by ichiriac** [comment]
@zxqfox this project is not fully finished but it's the most stable version I've made on the subject, FYI I've rewrite it from scratch 3 times using various frameworks, and migrating the original PHP grammar file for :

- pegjs : problems with look ahead 
- jison : various problems on classes
- hand written (this version) - LALR method

This version does not handles yet all the PHP grammar that's why it is on his early development stages , but for the implemented tokens it's solid rock.

There are some advantages to hand write a parser like :

- Understanding the parsing path and debug a grammar error
- Extending the grammar

I know that I loose some readability that's why I've written it in a way that most expressions are like a grammar instruction + the EBNF version of what it does on comments.

Is smarty parser not already a PHP lib ?

**Comment by ichiriac** [comment]
traits are now implemented and tested, open a new thread if you want to discuss about the stability of this lib

**Comment by zxqfox** [comment]
@ichiriac :+1: Thanks!

p.s. It is, and it has plex (php lex) grammar, but their compiler has no AST generation, it's integrated into smarty classes, and it's written on PHP. But I need AST. ;-)

**Comment by ichiriac** [comment]
@zxqfox not sure to understand why you look into a nodejs lib to work with a PHP lib, any way, after some releases, the lib is now much more stable
