### ISSUE TITLE
Cast to null is not a cast

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#103]
Now that the PR #102 is merged, I have another question concerning casts. I noticed that `(unset) $foo` is parsed as an `unset` node instead of a cast node with type `unset`. While this is workable for the prettier integration, i still found it a bit confusing - especially because the difference bettween the unset cast and a regular call like `unset($foo)` is just that the first one has a single node in `arguments`, while the second one has a list.
Thanks in advance :smile:

**Comment by ichiriac** [comment]
Noooo, it's not good to prettier, it's a real BUG, I may did not pay enough attention on it !!!

```
Example #2 Using (unset) casting

(unset) casting is often confused with the unset() function. (unset) casting serves only as a NULL-type cast, for completeness. It does not alter the variable it's casting.
```
from : http://php.net/manual/en/function.unset.php

Here a testing code :
https://astexplorer.net/#/gist/c5098fd3b19f3c0da9de29986aa553d9/faff581d39f825cf78111278d0048055a3dd031b

The two nodes are the same, you can see the cast as the same way to say NULL (just a synonym), it's just useless, so that's a critical bug.

**Comment by czosel** [comment]
Alright, then i'll happily scrap the workaround i had implemented locally! :smile:

**Comment by ichiriac** [comment]
thanks @czosel, it's now fixed

**Comment by czosel** [comment]
That was quick! Thanks a lot :+1:
