### ISSUE TITLE
Unhandled native identifiers

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#113]
The list of valid php type for type hinting function calls is here: http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types

It appears the parser currently handles everything except for `array` and `callable` (it interprets these as user-defined fully qualified names

**Comment by mgrip** [comment]
Hm looks like this might actually be intentional? https://github.com/glayzzle/php-parser/blob/master/src/parser/function.js#L242

I might just not understand how `name` is supposed to be interpreted [here](https://github.com/glayzzle/php-parser/blob/master/docs/AST.md#identifier). For array and callable the value of `name` is `\array` and `\callable`, as opposed the other types which just end up as `int`, `string`, etc

**Comment by ichiriac** [comment]
sorry, I did not have time to check on this issue, I'll be back on it later, but I think it was intentional because an array should be seen as a typing, and the `FQN` fully qualified name force to search the class from the root namespace, that's why the `\array` name. The `int` and `string` are forget classes.

![image](https://user-images.githubusercontent.com/173203/36691427-838b846e-1b35-11e8-88fe-f9a16199c22e.png)
 
My first approach was to make an interpreter so this interpretation was in order to make easier the implementation of an interpreter, but in this case it's breaking the file representation - I may certainly introduce a new AST nody type like a `ScalarType`

**Comment by evilebottnawi** [comment]
@ichiriac also we have problem with

```php
function int(int $var) {}
function int(iNt $test) {}
```

It is hard to detect when people use class`iNt` when `int` scalar. I think introduce new nod will be great and solve the problem.

**Comment by ichiriac** [comment]
released under `php-parser@3.0.0-prerelease.6`
