### ISSUE TITLE
DocBlock identification

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#114]
DocBlock seem to be identified by the starting `/**` and following whitespace. This leads to the following edge case (from https://github.com/prettier/prettier-php/issues/30):
```
/**************
 * test       *
 **************/
```
is parsed as
```
{
  "kind": "doc",
  "isDoc": false,
  "lines": [
    "*************\n * test       *\n *************"
  ]
}
```
and
```
// a
// b
```
becomes
```
{
  "kind": "doc",
  "isDoc": false,
  "lines": [
    "a",
    "b"
  ]
}
```
Which makes it hard to re-print them the way they were found. Similarly, i can also not tell the difference between `/* a */` and `// a` in the AST.

Maybe it would make sense to change the `isDoc` flag to just return true whenever `/* ... */` syntax is used? Or add another flag?

**Comment by ichiriac** [comment]
maybe we should do something similar to https://github.com/glayzzle/php-parser/issues/116 ?

**Comment by czosel** [comment]
Yes, good idea! :smile:

**Comment by mgrip** [comment]
I'm not sure that would solve the problem?
```php
/**************
 * test       *
 **************/
```
^This should still be considered a doc block right? (which I assume `isDoc` is meant to represent)

**Comment by ichiriac** [comment]
Hi @mgrip,

This will be fixed in the next release. The `isDoc` was removed, and I've introduced 2 new nodes `CommentLine` or `CommentBlock`.

I stopped to trim them, so you will have the raw comment node `/** foo **/` or `# single line comment` ...

For more details take a look at https://github.com/glayzzle/php-parser/issues/126#issuecomment-370268380

**Comment by mgrip** [comment]
Thank you! 🙏
