### ISSUE TITLE
Inside double quotes offset interpreted always as string

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#124]
Input:
```php
$string = "He drank some $juices[koolaid1] juice.";
```
Output:
```json
"offset": {
  "kind": "string",
  "loc": {
    "source": null,
    "start": {
      "line": 3,
      "column": 33,
      "offset": 40
    },
    "end": {
      "line": 3,
      "column": 41,
      "offset": 48
    }
  },
  "value": "oolaid",
  "isDoubleQuote": false
}
```

I think it is should be "identifier".

**Comment by ichiriac** [comment]
you did not notice but there is a bigger/critical bug in your report :

![image](https://user-images.githubusercontent.com/173203/36858948-45205cc8-1d7d-11e8-9e9c-f12c916f652a.png)

Seems to be a bug in the lexer, but it should be already be found as it parses more than 40k files on various frameworks in order to cover every part...

**Comment by ichiriac** [comment]
BTW, I'm agree with your about your question on the identifier

**Comment by evilebottnawi** [comment]
@ichiriac oh, you are right :+1:

**Comment by ichiriac** [comment]
I'm using a `constref` node because `identifier` is only used for referencing a class name.
