### ISSUE TITLE
Comments grouped together strangely

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#132]
![image](https://user-images.githubusercontent.com/13454680/37344848-dbc47a92-26a1-11e8-9346-7262750fecc2.png)

Seems like if you have non-doc comment before/after a doc comment they all get grouped together, and you can't really tell them apart. I think I would sort of expect them to be separate nodes in the ast? But would love to hear what other people think

**Comment by ichiriac** [comment]
A doc comment must be start with `/**` in order to be so (php have this rule into it's lexer tokens directly). Here it's only a single line comment and another multi line comment.

Note that the parser will split into 2 comments if it's the case.

Get a try with the master version based on the future v3 version, https://glayzzle.com/php-parser/#demo I'm stopping the merge comments nodes in the next release.
