### ISSUE TITLE
3.0 missing comments in empty blocks

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#135]
input:
```php
<?php
class Foo
{
    public function bar()
    {
        // method body
    }
}

```

![image](https://user-images.githubusercontent.com/13454680/37487437-ed6e9eea-2867-11e8-88cd-45cfbb993e94.png)

**Comment by mgrip** [comment]
Ah nvm I think I'm just misunderstanding the new api

**Comment by ichiriac** [comment]
Hi Mike,

As in the body you don't have any node, comment is not attached as leading comment on nothing. It will still be present in the `comments` array attached on the program root node, but not present in the function body node.

I've played a little with babylon in order to see how they handle this, and they use a `innerComments` on the body only if the function is empty. Maybe a bug, but seems to change it's behaviour if you add a comment after the function.

Tell me if you can handle this from the `comments` array by filtering comments with the function offsets or you need an helper.

In this case, I would create an `comments` property on every block node, and automatically add comments on each sub nodes (more consistent with the program node behaviour)

**Comment by mgrip** [comment]
@ichiriac thanks for the response! Confirmed I'm able to use the outer `comments` array just using the offsets. Thanks for investigating!

**Comment by ichiriac** [comment]
hi @evilebottnawi, I've did not work on the project for a while. I plan to work on it again soon (in 1 or 2 weeks), I have a pending release to do and this bugfix will be included.
