### ISSUE TITLE
Method location wrong?

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#141]
PHP Script :
```php
<?php

class Foo
{
    public function setTitle($title){}

    /**
     * Comment
     */
    public function someMethod() {}
}
```

AST Structure of first method:
```json
        {
          "kind": "method",
          "loc": {
            "source": null,
            "start": {
              "line": 5,
              "column": 11,
              "offset": 30
            },
            "end": {
              "line": 9,
              "column": 7,
              "offset": 89
            }
          }
```

I would have expected the `end` location of the first method to be on line 5 as well (instead of line 9)

https://github.com/prettier/plugin-php/issues/250

**Comment by ichiriac** [comment]
This is a generic bug. I must review each `next` statement on every parsing function. 

The nodes builder automatically resolves locations based on current token. The fact to execute the node builder node and to execute a next before it make it include the next token into location.

**Comment by ichiriac** [comment]
Hi @czosel,

It's fixed, it was a problem with the fact I was using comments nodes like any node and they introduced as position locations.

Remains to check every node in order to be sure that fully corrected. For information, the algorithm is based on a token ahead parser. The parsing principle is the following :

- read the ̀next` token
- depending on the token choose a parsing function
- the function creates a new `node` ctor
- use the `next` to consume current token and go to the next
- when finished execute the node ctor

If the next statement is used at the wrong location, it will use bad locations, so

**Comment by czosel** [comment]
Hi @ichiriac, awesome! Thanks both for the bugfix and for the explanation :smile:
