### ISSUE TITLE
staticlookup is broken with curly

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#167]
Input:
```php
$var = Foo::{$bar['baz']}();
```

Output: `SyntaxError: Parse Error : syntax error, unexpected '{' on line 35`

**Comment by evilebottnawi** [comment]
/cc @ichiriac I have some question about this?

`Foo::{$bar['baz']}();` is parsed now and we have valid ast, but 
`Foo::$bar['baz']();` is parsed now too, but we have invalid ast.

Now we have same ast, but for second should be:
- call
  - offsetlookup 
    - staticlookup

Any ideas where i should fix it?

**Comment by ichiriac** [comment]
Related to https://github.com/glayzzle/php-parser/issues/233 from this merge https://github.com/glayzzle/php-parser/pull/225

You can read the explanation from the PR, it explains the bug, and if you don't find I'll fix it later, this is a minor bug

**Comment by ichiriac** [comment]
Ok, after reading again and trying with PHP, it's true about `new` keywords, but here we are dealing with `member_name`.

Here the php definition :

```
function_call:
		name argument_list
	|	class_name T_PAAMAYIM_NEKUDOTAYIM member_name argument_list
	|	variable_class_name T_PAAMAYIM_NEKUDOTAYIM member_name argument_list
	|	callable_expr argument_list
;
member_name:
		identifier
	|	'{' expr '}'
	|	simple_variable
;
identifier:
		T_STRING 
	| 	semi_reserved  
;
simple_variable:
		T_VARIABLE
	|	'$' '{' expr '}'
	|	'$' simple_variable
;
```
As you can see, `Foo::$bar['baz']();` is not a valid `class_name T_PAAMAYIM_NEKUDOTAYIM member_name` because of `['baz']`, but it's a `callable_expr`.

Next you need to run the code in step-by-step in order to understand the execution flow :

- node <- read_static_getter -> read_reference_variable -> eating []
- recursive_variable_chain_scan -> eating ()

The recursive_variable_chain_scan can also eat [] and it translates correctly nodes, so to fix this, you have just to disable the eating of `[]` into read_reference_variable, it was just too early
