### ISSUE TITLE
[discussion] `constref` vs `identifier`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#188]
Maybe we can avoid `constref` node and use `identifier` everywhere. Looks babylon do this, also it is more generic. It is remove unnecessary ast node.

Maybe related to https://github.com/glayzzle/php-parser/issues/183. I think better for `self`, `parent` and `static` use `identifier`.

Also related https://github.com/glayzzle/php-parser/issues/113.

**Comment by evilebottnawi** [comment]
Looks php parser interpreted this as `identifier` https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Identifier.php

**Comment by evilebottnawi** [comment]
Also maybe we can look on https://github.com/nikic/PHP-Parser/ and add new/modify/change some nodes, example they have `Stmt_Expression` node, introducing this node allow to detect when we execute code not in other `expression` (it is allow to print some nodes better in `prettier`)

**Comment by ichiriac** [comment]
Agree with the constref & identifier confusion, I just need to investigate on possible inconsistencies but I like the idea to simplify these nodes.

For the Stmt_Expression I need to take a closer look at how it's implemented and intended to express

**Comment by ichiriac** [comment]
I'm not totally agree with php-parser choices; mixing keywords and class names with the identifier node it's not clear - it provides a isSpecialClassName boolean in order to keep the distinction.

The babylon choice is to create a special node for each keyword :
![image](https://user-images.githubusercontent.com/173203/46585432-15c2c000-ca71-11e8-9b08-adb458dd2f43.png)

It's better, but it's maybe too much. To make it simpler, here some use cases :

- using a class, function, constant name (actually identifier) ==> becomes a new node like Reference
- a special keyword (static, self, parent...) ==> becomes a new node like Keyword
- a property name (actually constref) ===> becomes Identifier
- a function,  declaration name ===> becomes Identifier

I want to distinguish Identifier and Reference because of namespace resolution property, and the Reference is a special use case (it refers to a declared structure)

What's your opinion @evilebottnawi ?

**Comment by evilebottnawi** [comment]
Sound good for me

**Comment by ichiriac** [comment]
Now we have `identifier` for usual names and the reference node for others : 

 - Reference
   - TypeReference : available soon (for basic type hints like int, array...)
   - ParentReference : parent keyword
   - StaticReference  : static keyword
   - SelfReference  : self keyword
   - ClassReference  : class name usage

**Comment by ichiriac** [comment]
released under `php-parser@3.0.0-prerelease.6`
