### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by mrjoelkemp** [glayzzle/php-parser#2]
Love the idea behind this module. I'd love to use it to extract the dependencies of a php file (i.e., any traits, `include`d/`require`d files, namespaces). 

Would be great if the following were possible:

1. Invoke the parser on code that has an opening <?php tag without an error being thrown:
![image](https://cloud.githubusercontent.com/assets/865203/8999866/24cf04b8-370e-11e5-8e62-47baef27e52b.png)
1. Get back an AST that is in an object form instead of a nested list. This would have the PHP AST in the same data structure as JavaScript ASTs (produced by libs like Esprima). I could then reuse a tree walker lib to traverse objects instead of nested lists. 
1. Parts of the test.php file really should be converted into a node binary script: create a `bin/cli.js` file that resembles (https://github.com/mrjoelkemp/node-dependents/blob/master/bin/dependents.js). This should allow folks to get an ast by supplying a filename via the cli. Your cli script would then read the contents of the file, pipe it to the parser, then pipe the AST to the console.
1. Related to ^^, you can just omit the hand-rolled argument handling by using [commander](https://www.npmjs.com/package/commander). It's battle-tested, already does what you want, and cuts down on the amount of code one has to sift through when looking at the binary file.

I'm happy to help make this lib into a more friendly node module. However, I need your expertise to achieve the second request.

**Comment by ichiriac** [comment]
Hi,

Glad to see that you're interested by this project. I plan to start a new project very similar to the PHP reflection API based on this parser. I'll start it in a few weeks at https://github.com/glayzzle/php-reflection.

To reply at your questions :

1. To parse code (with open tags) you have to use the parseCode function instead the parseEval :
(see https://github.com/glayzzle/php-parser/blob/master/main.js) - You seem to include directly the src/parser.js from you cli.js (line 9), you shoud `require 'php-parser'` lib -> ./node_modules/php-parser/main.js and then use the parseCode function.
2. Agree with the object approach but not from the AST. I want to keep the AST memory efficient and that's why I only use nested lists. I have to start a spec but take for granted that the first place in any array is a string that define it's type. But I am agree with you that nested lists are not efficient enough to work with, that's why I need another layer/lib to interpret the AST, that's the next library php-reflection.
3. & 4 - Thanks for the advice (I will use it on glayzzle which is the end product). You seem to think that this lib could be used as a standalone utility. The bin folder (and scripts) is only for the developpement stage of the lib (and the code was made in hurry just to validate the lib - they are even not deployed with npm : https://github.com/glayzzle/php-parser/blob/master/.npmignore) - so if for example you would have a cli that take a file and outputs his AST, you should create a new project for that.

So for now I need to start a documentation for all the AST structure on the wiki (after that I'll release the lib on a 1.x version - the AST API will be definitive)

Some tips to help you start with the AST :

['namespace', [...path of the namespace...], [...instructions...] ]

[ 'sys', 'require' | 'include_once' | ... , [argument]]
> the argument can be a string like : [ 'string', 'baz.php' ], or an expression

To continue use a file to experiment AST results : 

```
<?php

namespace boo\bar {

  trait baz {
    function run() {
      return true;
    }
  }

  trait foo {
    function run() {
      return true;
    }
    function stop() {
      return true;
    }
  }

  trait foobaz {
    use foo, baz {
      baz::run insteadof foo;
    }
  }

}

namespace foo {

  require 'baz.php';
  include_once 'foobar.php';

  use org\apache\spring\blabla as CoolThing;

  abstract class bar extends CoolThing {
    use boo\bar\foo, boo\bar\baz {
      boo\bar\foo::run insteadof boo\bar\baz;
    }
  }
}
```

And get the AST from the command line : ../bin/> node test.js -f ../test/proto/test3.php -v

**Comment by mrjoelkemp** [comment]
Thanks a ton for the insight @ichiriac. I really appreciate it.
