### ISSUE TITLE
[bug] invalid ast for `const`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#210]
Input:
```php
const CONSTANT = 'Hello', TEST = 'world';
```

Output each `const` as separate item, but should have same ast as for `static`. I will look how we can fix it.

**Comment by ichiriac** [comment]
Here some hints because you have multiple parts to change : 

You can start here : https://github.com/glayzzle/php-parser/blob/eed5703f242e0fc0acd057487a1dbf0c992c83f9/src/parser/statement.js#L64

You may have a location problem with this node

You have to change the way this function works by changing the node instanciation : https://github.com/glayzzle/php-parser/blob/eed5703f242e0fc0acd057487a1dbf0c992c83f9/src/parser/statement.js#L105

You may have to change the signature of the AST node :
https://github.com/glayzzle/php-parser/blob/master/src/ast/constant.js

1. You can use the expression statement with this node as it expects the endOfStatement : 
https://github.com/glayzzle/php-parser/blob/eed5703f242e0fc0acd057487a1dbf0c992c83f9/src/parser/statement.js#L121

Note : every expression waiting an endOfStatement should be wrapped on an expressionstatement node.

2. You may need to create a new ConstantDeclaration node extending the Expression Node, having a list of constant nodes.
After declaring the new node into its file you have to register it here : https://github.com/glayzzle/php-parser/blob/eed5703f242e0fc0acd057487a1dbf0c992c83f9/src/ast.js#L341

3. Use the new node into the `read_const_list` function

**Comment by ichiriac** [comment]
After you will have to also migrate const keyword from classes :
https://github.com/glayzzle/php-parser/blob/master/src/parser/class.js#L80

In order to do this, you have to create a ClassConstantDeclaration (that replaces the ClassConstant usage) extending the ConstantDeclaration and introducing the visibility flag.
