### ISSUE TITLE
[question] `call` use `classreference`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#228]
I find what `call();` output `classreference` in `what`? It is expected? Why it is not `identifier`? Should we use `classreference` for `class`/`interface`/`trait` names?

**Comment by ichiriac** [comment]
the reason why it's a class reference is because of namespaces resolutions. Maybe the name of the node is bad, we could change it to IdentifierReference, meaning it's referring to something related on namespaces resolution. It could be a constant, function, or a class, or a class constant, or a class method.

**Comment by ichiriac** [comment]
take this example, same result, but not the same code :

```php
<?php
namespace {
  call();
  \call();
  namespace\call();
}
```

It's a function, but the same node can be used for a constant usage, or a class.
