### ISSUE TITLE
Dependency bundling for `@now/php`

### ISSUE THREAD

**Issue by rauchg** [glayzzle/php-parser#244]
It would be really cool to investigate the viability of doing something similar to webpack, but for PHP scripts!

This seems like a great starting point: https://github.com/glayzzle/php-parser

**Comment by evilebottnawi** [comment]
@rauchg what do you mean? Can you describe more verbosely?

**Comment by ichiriac** [comment]
Not sure what your idea is about, webpack being for providing nodejs modules on browser, it may be something about providing php on browser.

You can start by taking a look at these projets :
- https://francisco.io/blog/running-php-in-javascript/
- https://gitlab.com/kornelski/babel-preset-php
- https://github.com/glayzzle/php-expressjs
- https://github.com/glayzzle/php-transpiler
- https://github.com/glayzzle/php-core
- https://github.com/glayzzle/php-runtime
- https://github.com/glayzzle/glayzzle

The first reason I've started the project years ago (and made this parser) was for running PHP syntax on NodeJS. The project is paused because of my lack of time, but it will exist in the future.

It's hard technically but it's not impossible. 

PHP Runtime uses php-transpiler to convert PHP to JS, and uses PHP Core to provide the same functions as PHP on JS, and it's provide an abstract execution layer in order to mimick PHP behavior. Glayzzle it's just a wrapper to launch scripts from the CLI. That approach provides a consistent way to be close to what you can do from with the PHP engine, but it's not potable to the web because of the framework overhead. Its purpose is to be run from NodeJS.

On the other hand you have bable-preset-php which only translates PHP syntax to JS syntax, meaning you almost don't have backward support on PHP framework, but it's a good approach for publishing a PHP script on the web.

All of theses projects avec just proof of concepts and are not finished or for a production grade, but fell free to join any of these or share your ideas.
