### ISSUE TITLE
can't parser as inline node

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#263]
Input:

```php
<?php$var = 1;
?>
```

throw 
```
 SyntaxError: Parse Error : syntax error, unexpected '$var' (T_VARIABLE), expecting ';' on line 1
```

but should parse as inline node

**Comment by ichiriac** [comment]
I'll check it

**Comment by ichiriac** [comment]
The behavior is correct, but the default is not. 

On php by default `short_open_tag` are false, here the result if I enable them :
```
$ php -i | grep short
short_open_tag => On => On
$ php test/debug.php 
PHP Parse error:  syntax error, unexpected '$var' (T_VARIABLE) in .../glayzzle/php-parser/test/debug.php on line 1
```

And here when they are disabled :
```
$ php -i | grep short
short_open_tag => Off => Off
$ php test/debug.php 
<?php$var = 1;
?>
```

Default options on the lexer are :
```
  this.asp_tags = false;
  this.short_tags = true;
  this.php7 = true;
```

With `short_tags` to false you have the expected behavior. I'll put it to false by default as we are in PHP7 by default
