### ISSUE TITLE
still invalid ast for list with multiple `,`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#358]
Invalid ast:

Input:
```
list(0 => $var,) = $arr;
```

Should no `noop` element in this case

we need null/`noop` if two or more `,`

**Comment by evilebottnawi** [comment]
It is break our prettier in many cases, now we have `noop` before `identifier` in `use`/`new`/etc

**Comment by evilebottnawi** [comment]
hm, maybe i am wrong, investigate

**Comment by evilebottnawi** [comment]
Yes, invalid ast:

Input:
```
list(0 => $var,) = $arr;
```

Should no `null` element in this case

**Comment by evilebottnawi** [comment]
we need null/`noop` if two or more `,`

**Comment by evilebottnawi** [comment]
We can't update parser due this problem

**Comment by evilebottnawi** [comment]
We don't need node for this case because we can find trailing comma using `loc` and source code, so node is unnecessary for this

**Comment by ichiriac** [comment]
Hi @evilebottnawi, could you please provide more informations on what it breaks on your code to add a node that represent the actual state of the document.

**Comment by evilebottnawi** [comment]
@ichiriac same code should output same ast, i.e. ast from `['1', '2']` should be same `['1', '2', ]`, but now we have difference ast, it is invalid, also you can check other parsers (not only for js) and they don't add the node for a trailing comma.

How we check what prettier works right. Get a code -> parser and format -> compare an ast from original code and formatted code, if something difference means what we break code, with `noop` code it happens.

Ast information should be deterministic, with noop node it is not.

**Comment by ichiriac** [comment]
Hi @evilebottnawi, thanks, I understand better why it matters. Do you agree that `[$a, $b, , ]` is the same also as `['1', '2']` - if yes, in that case the answer to my question on https://github.com/glayzzle/php-parser/pull/367#issuecomment-525514522 is that we should avoid using at all noop on list elements, so trimming everything.

But take care, it will be harder to keep comments on code like this `[$a, $b, /* foo */ , /* bar */ ]`

Agree that AST is deterministic, but if I start on that way, he will strip too much informations on some cases and we need them for formating for example...

**Comment by evilebottnawi** [comment]
`[$a, $b, , ]` !== `[$a, $b, ]`
in `[$a, $b, , ]` case we need only one `noop` node, we don't lose comment because we have `noop` node, latest (`bar` in example above) should be assign to `array` node (it is same as we do for `[/* Comment */]`)

**Comment by ichiriac** [comment]
ok, `[$a, $b, , ]` is invalid :

```
php -r "var_dump([1,2,,]);"
PHP Fatal error:  Cannot use empty array elements in arrays in Command line code on line 1
```
> Note that it's not a parsing error, it's handled at the runtime level, but as it's not allowed I could add a parse error for that case

- on lists : `list($a, $b, ,) = [1, 2, 3, 4]` is the same as `list($a, $b) = [1, 2, 3, 4]` (and allowed)
- on other syntax : `use a, b, ;` is the same as `use a, b;` (and the parser don't add noop), 
> Note the `use a, b, , ;` is invalid, same as arrays

I think the best thing to do is to add noop when it's needed each time we find an empty node, and then for your tests you can filter from the input/output AST the noop node, so your check don't look at noop nodes (as you may strip them)

**Comment by evilebottnawi** [comment]
Using `[$a, $b, , ]` i mean `list`, it is very inconsistently, we should add `noop` for `use a, b, ;` also, or avoid `noop` node in all cases.

Please look other parser, no one parser added `null`/`noop` for last trailing comma, we use hack in prettier for removing this unnecessary node, other tool will do same, because it is unnecessary. PHP parser also avoid unnecessary `null`/`noop` node for last trailing comma. I don’t understand what the problem is and why we need this extra node :disappointed:

**Comment by ichiriac** [comment]
My problem is that after releasing a change with or without noop, it's hard to change the choice (until a new major release).

As it's definitive, if you pick the wrong option you may miss an use case that could lead to either avoid the option, use a bad design, or create a major release just for a little change.

That's why I take time in order to fully understand pros and cons, but on this I only want a clean rule. Here the output of Javascript :

![Screenshot from 2019-08-31 03-40-47](https://user-images.githubusercontent.com/173203/64057749-315f1980-cba1-11e9-93ca-db3094b6f80d.png)

They use `null`, and strip only the last one. `[1, 2]` == `[1,2,]` but `[1,2,,]` == `[1,2,null]`

1. I fully understand why they do that, the AST represents the resulting value, the latest null is stripped when creating the array

2. If the last value is not a null it's not stripped : `[1,2,,,5]` == `[1,2,null,null,5]`

I'm not agree with the `null` usage, in order to avoid null errors, handle location, or comments, like in typescript parser whom use `OmmitedExpression` 

![Screenshot from 2019-08-31 04-35-18](https://user-images.githubusercontent.com/173203/64058268-dc270600-cba8-11e9-9c27-62ca4fd6a835.png)

So here a generic rule proposal for any case :

- using allways `noop`, and avoid `null`
- on arrays, stripping the last `noop` if present
- if stripping the last noop, set `hasTrailingComma` to `true` (as in typescript)

This rule may be applied on every node involving the strip of the trailing comma.

Only one edge case, by stripping the last trailing comma, we strip a node, and possibly lose the attached comment, so we could provide an extra ast option on the parser `stripTrailingComma` with the default option `true` and handle this edge case also.

If you're good to go with this, lets implement it

**Comment by evilebottnawi** [comment]
> if stripping the last noop, set hasTrailingComma to true (as in typescript)

:+1:
