### ISSUE TITLE
Cleanup the code

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#50]
- [x] Add "use strict" statement on every file
- [x] Check & investigate each @todo / @fixme statement
- [x] Pass with JSHint on every file
- [x] Use ES6
- [x] Add a transpiler for ES5 support

**Comment by ichiriac** [comment]
Hi @czosel,

I would be really glad if you can help on this. When the project was started es6 was not mature but I agree that I should start to migrate on it.

I have no problem with ES6 (to be honest I do not like the class support as it shadows the prototypal power of JS), but I would be glad to use all ES6 goodies. 

I just need to support browser with babel for example, and be compliant with node v4.

**Comment by czosel** [comment]
Hi @ichiriac, 
Awesome! I'll definitely try to make some first steps in this direction. I actually also don't like ES6 classes too much myself, but it's hard to live without many of the other features (say arrow functions). Since you have a build step already, compiling down to ES5 for support in IE11/Node v4 should be no problem. Rewriting the whole thing to ES6 is probably a big task, so I'd suggest introducing some ESLint rules that throw warnings when old syntax is found. What do you think?

**Comment by ichiriac** [comment]
Agree with you, as sometimes big refactoring can lead to regressions. The ESLint automated check is a must have. You can start by providing just a simple configuration that checks common rules and attach it on travis build steps :smile:
