### ISSUE TITLE
Parser breaks when extracting comments

### ISSUE THREAD

**Issue by rasmusbe** [glayzzle/php-parser#55]
Hi,

Got an bug report to https://github.com/rasmusbe/wp-pot/ that seems to be a problem in php-parser.

When parsing with extracting comments activated this file breaks:
http://pastebin.com/gisRzWdz

If I remove the comment on line 70 it works but it should work with the comment as well.

/Rasmus

**Comment by ichiriac** [comment]
Hi @rasmusbe,

The bug is now fixed and released under `1.0.4`. Initially the parser was not made in order to parse and extract comments (you can find more informations here : https://github.com/glayzzle/php-parser/issues/6#issuecomment-182536365)

I need to improve tests over this options, it's not yet stable, it's actually passing IF/TRY statements, but need to test for/do/while/switch ... etc ...

If you just need to extract informations from code, and do not need comments, it would be safer to disable comments extraction.

**Comment by rasmusbe** [comment]
Thank you! Tried 1.0.4 and it works. 

I don't see a release for 1.0.4 in the repo, is the changes not pushed to the repo?

**Comment by ichiriac** [comment]
The changes are pushed on the develop branch, and I've released them directly on NPM (https://github.com/glayzzle/php-parser/tree/develop). 

I'll make a release on major/minor changes (next is 1.1.x) with github in order to create a tag and a branch, but in order to avoid too many releases each bugfix will on develop branch / major+minor branch (with pull request from develop) and just released to NPM - following [SEMVER](http://semver.org/).
