### ISSUE TITLE
Improve & test the tolerant mode

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#60]
Need to implement something similar :
https://github.com/Microsoft/tolerant-php-parser/blob/master/docs/HowItWorks.md#error-tokens

Actually, unexpected tokens are directly skipped, so a bracket can break all structure.

Initial discussion : 
https://github.com/glayzzle/php-parser/issues/11

**Comment by mousetraps** [comment]
Hey @ichiriac! Been tracking this project since @nevadascout's Crane extension depends on this parser, and we want to help fuel the ecosystem where we can. We chose to write tolerant-php-parser in PHP, but we really like what you're doing, and want to ensure our learnings can be made useful for you as well. It would also be awesome to hear about some of the issues you've been running into first hand. Would you guys be interested in setting up a Skype call to discuss?

**Comment by ichiriac** [comment]
Hi @mousetraps and @nevadascout,

I really would love to speak with you both, my skype is ioan.chiriac14. We can also use https://gitter.im/glayzzle/Lobby - that's the public chat room of the project.

As you prefer, but try to connect the morning because of jet lag (9 hours).
