### ISSUE TITLE
Not parse variables in comment?

### ISSUE THREAD

**Issue by zertex** [glayzzle/php-parser#98]
Not parse variables in comment?

Ex.:
`
// @var $superVar array
/* @var $superVar array */
/**  @var $superVar array */
`

**Comment by ichiriac** [comment]
Hi @zertex,

This parser just extacts documentation nodes as a list of text lines : https://astexplorer.net/#/gist/c5098fd3b19f3c0da9de29986aa553d9/e391f0aa3d006d9f753e7a69cdd01ab66609db08

In order to obtain the documentation AST nodes you have to use another library specialy made for that part : https://github.com/glayzzle/doc-parser

> Note : as @var is not supported by default you have to say to that parser how to parse it with a configuration :

```js
var reader = new DocParser({
  'var': [
    {
      property: 'name',
      parser: 'variable'
    },
    {
      property: 'type',
      parser: 'type'
    },
    {
      property: 'description',
      parser: 'text',
      optional: true,
      default: ''
    }
  ]
});
var data = reader.parse('/** @var $foo string some description */');
```

> Note : `reader.parse` can take directly an array of strings like php-parser lines property on doc nodes.

That way, you will retrieve a node structure like this :

```
{
  kind: 'doc',
  summary: 'Some description retrieved from the first line of the coment',
  body: [
    {
      kind: 'var',
      name: 'foo',
      type: 'string'
    }
  ]
}
```

Hope you will find what you need,
Ioan

**Comment by zertex** [comment]
Thanks!
